version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "50000:50000"
    networks:
      - devops-net
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

  mongo:
    image: mongo:6.0
    container_name: mongo
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    networks:
      - devops-net

  backend:
    image: galhillel/devops-project-backend:latest
    container_name: backend
    restart: unless-stopped
    env_file:
      - ./server/.env
    environment:
      - MONGO_URI=mongodb://mongo:27017/devops-project
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    networks:
      - devops-net

  frontend:
    image: galhillel/devops-project-frontend:latest
    container_name: frontend
    restart: unless-stopped
    environment:
      - VITE_API_URL=http://backend:5000/api
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - devops-net

volumes:
  mongo-data:
  jenkins-data:

networks:
  devops-net:
    driver: bridge
