services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    networks:
      - devops-net

  backend:
    image: galhillel/devops-project-backend:latest
    container_name: backend
    restart: unless-stopped
    env_file:
      - ./server/.env
    environment:
      - MONGO_URI=mongodb://mongo:27017/devops-db
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    networks:
      - devops-net

  frontend:
    image: galhillel/devops-project-frontend:latest
    container_name: frontend
    restart: unless-stopped
    environment:
      - VITE_API_URL=http://backend:5000/api
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - devops-net

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins-server
    restart: unless-stopped
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    networks:
      - devops-net 

volumes:
  mongo-data:

networks:
  devops-net:
    driver: bridge
