name: build-and-lint
# This is the name of the workflow. You will see it in the Actions tab on GitHub.

on:
  push:
    branches: [main, dev]  # Trigger workflow on push to main or dev branches
  pull_request:
    branches: [main, dev]  # Trigger workflow when a PR targets main or dev

jobs:
  build-and-lint:           # Define a job called "build-and-lint"
    runs-on: ubuntu-latest  # Run the job on the latest Ubuntu VM

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        # Checks out your repository so the workflow can access the code

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20
        # Installs Node.js version 20 on the runner

      - name: Install backend dependencies
        working-directory: server
        run: npm ci
        # Installs backend dependencies from package-lock.json in a clean way

      - name: Lint backend
        working-directory: server
        run: npm run lint -- --max-warnings=0
        # Runs ESLint on the backend code. Fails if there are warnings or errors

      - name: Install frontend dependencies
        working-directory: client
        run: npm ci
        # Installs frontend dependencies in the client folder

      - name: Lint frontend
        working-directory: client
        run: npm run lint -- --max-warnings=0
        # Runs ESLint on the frontend code. Fails if there are warnings or errors

      - name: Build backend image
        run: docker build -t backend ./server
        # Builds a Docker image for the backend using the server Dockerfile

      - name: Build frontend image
        run: docker build -t frontend ./client
        # Builds a Docker image for the frontend using the client Dockerfile
